server:
  port: 8080


#server：
#  port=8080
#spring.application.name = Server-Provider
##是否注册到服务器
#eureka.client.register-with-eureka = true
##是否获取服务端数据
#eureka.client.fetch-registry = true
##指定服务器地址
#eureka.client.service-url.defaultZone = http://localhost:8090/eureka/,http://peer1:8091/eureka/
##eureka.client.service-url.defaultZone = http://localhost:8090/eureka/
spring:
  application:
    name: Server-Provider
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://root:123456@peer1:8091/eureka/,http://root:123456@peer2:8092/eureka/
#开启第二个服务
# cd SpringCould-02/target
# java -jar  demo-0.0.1-SNAPSHOT.jar --server.port=8081